version: '3'

services:
  backend:
    image: mcr.microsoft.com/devcontainers/go:dev-1.21
    restart: unless-stopped
    volumes:
      - .:/workspace:cached
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      SQLX_CONN_STRING: "host=postgres port=5432 user=proglv password=proglv dbname=proglv sslmode=disable"
      AMQP_CONN_STRING: "amqp://proglv:pass@rabbitmq:5672/"
      REDIS_CONN_STRING: "redis:6379"
    ports:
      - "3001:3001"
    command: ["sleep", "infinity"]

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: proglv
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: proglv
      POSTGRES_USER: proglv
      POSTGRES_DB: proglv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "proglv"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@programme.lv'
      PGADMIN_DEFAULT_PASSWORD: 'proglv'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  rabbitmq_data:
  redis-data:
  postgres_data:
  pgadmin_data:

