version: '3'

services:
  r-proxy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./r-proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  website:
    build: .
    restart: unless-stopped
    volumes:
      - .:/workspace:cached
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["sleep", "infinity"]

  backend:
    build: .
    restart: unless-stopped
    volumes:
      - .:/workspace:cached
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      SQLX_CONN_STRING: "host=postgres port=5432 user=proglv password=proglv dbname=proglv sslmode=disable"
      AMQP_CONN_STRING: "amqp://proglv:pass@rabbitmq:5672/"
      REDIS_CONN_STRING: "redis:6379"
    ports:
      - "3001:3001"
    command: ["sleep", "infinity"]

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: proglv
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: proglv
      POSTGRES_USER: proglv
      POSTGRES_DB: proglv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "proglv"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass


configs:
  pgpass:
    content: postgres:5432:*:proglv:proglv
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "proglv local",
        "Host": "postgres",
        "Port": 5432,
        "MaintenanceDB": "proglv",
        "Username": "proglv",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}

volumes:
  rabbitmq_data:
  redis-data:
  postgres_data:
  pgadmin_data:
  caddy_data:
  caddy_config:


